class CountryOption {
  final String code;
  final String name;
  final String dialCode;
  final String flag;

  const CountryOption({
    required this.code,
    required this.name,
    required this.dialCode,
    required this.flag,
  });
}

class CountryConfig {
  static const List<CountryOption> countries = [
    CountryOption(
      name: "Afghanistan",
      code: "AF",
      dialCode: "+93",
      flag: "🇦🇫",
    ),
    CountryOption(name: "Albania", code: "AL", dialCode: "+355", flag: "🇦🇱"),
    CountryOption(name: "Algeria", code: "DZ", dialCode: "+213", flag: "🇩🇿"),
    CountryOption(
      name: "American Samoa",
      code: "AS",
      dialCode: "+1-684",
      flag: "🇦🇸",
    ),
    CountryOption(name: "Andorra", code: "AD", dialCode: "+376", flag: "🇦🇩"),
    CountryOption(name: "Angola", code: "AO", dialCode: "+244", flag: "🇦🇴"),
    CountryOption(
      name: "Anguilla",
      code: "AI",
      dialCode: "+1-264",
      flag: "🇦🇮",
    ),
    CountryOption(
      name: "Antarctica",
      code: "AQ",
      dialCode: "+672",
      flag: "🇦🇶",
    ),
    CountryOption(
      name: "Antigua and Barbuda",
      code: "AG",
      dialCode: "+1-268",
      flag: "🇦🇬",
    ),
    CountryOption(name: "Argentina", code: "AR", dialCode: "+54", flag: "🇦🇷"),
    CountryOption(name: "Armenia", code: "AM", dialCode: "+374", flag: "🇦🇲"),
    CountryOption(name: "Aruba", code: "AW", dialCode: "+297", flag: "🇦🇼"),
    CountryOption(name: "Australia", code: "AU", dialCode: "+61", flag: "🇦🇺"),
    CountryOption(name: "Austria", code: "AT", dialCode: "+43", flag: "🇦🇹"),
    CountryOption(
      name: "Azerbaijan",
      code: "AZ",
      dialCode: "+994",
      flag: "🇦🇿",
    ),
    CountryOption(
      name: "Bahamas",
      code: "BS",
      dialCode: "+1-242",
      flag: "🇧🇸",
    ),
    CountryOption(name: "Bahrain", code: "BH", dialCode: "+973", flag: "🇧🇭"),
    CountryOption(
      name: "Bangladesh",
      code: "BD",
      dialCode: "+880",
      flag: "🇧🇩",
    ),
    CountryOption(
      name: "Barbados",
      code: "BB",
      dialCode: "+1-246",
      flag: "🇧🇧",
    ),
    CountryOption(name: "Belarus", code: "BY", dialCode: "+375", flag: "🇧🇾"),
    CountryOption(name: "Belgium", code: "BE", dialCode: "+32", flag: "🇧🇪"),
    CountryOption(name: "Belize", code: "BZ", dialCode: "+501", flag: "🇧🇿"),
    CountryOption(name: "Benin", code: "BJ", dialCode: "+229", flag: "🇧🇯"),
    CountryOption(
      name: "Bermuda",
      code: "BM",
      dialCode: "+1-441",
      flag: "🇧🇲",
    ),
    CountryOption(name: "Bhutan", code: "BT", dialCode: "+975", flag: "🇧🇹"),
    CountryOption(name: "Bolivia", code: "BO", dialCode: "+591", flag: "🇧🇴"),
    CountryOption(
      name: "Bosnia and Herzegovina",
      code: "BA",
      dialCode: "+387",
      flag: "🇧🇦",
    ),
    CountryOption(name: "Botswana", code: "BW", dialCode: "+267", flag: "🇧🇼"),
    CountryOption(name: "Brazil", code: "BR", dialCode: "+55", flag: "🇧🇷"),
    CountryOption(
      name: "British Indian Ocean Territory",
      code: "IO",
      dialCode: "+246",
      flag: "🇮🇴",
    ),
    CountryOption(
      name: "British Virgin Islands",
      code: "VG",
      dialCode: "+1-284",
      flag: "🇻🇬",
    ),
    CountryOption(name: "Brunei", code: "BN", dialCode: "+673", flag: "🇧🇳"),
    CountryOption(name: "Bulgaria", code: "BG", dialCode: "+359", flag: "🇧🇬"),
    CountryOption(
      name: "Burkina Faso",
      code: "BF",
      dialCode: "+226",
      flag: "🇧🇫",
    ),
    CountryOption(name: "Burundi", code: "BI", dialCode: "+257", flag: "🇧🇮"),
    CountryOption(name: "Cambodia", code: "KH", dialCode: "+855", flag: "🇰🇭"),
    CountryOption(name: "Cameroon", code: "CM", dialCode: "+237", flag: "🇨🇲"),
    CountryOption(name: "Canada", code: "CA", dialCode: "+1", flag: "🇨🇦"),
    CountryOption(
      name: "Cape Verde",
      code: "CV",
      dialCode: "+238",
      flag: "🇨🇻",
    ),
    CountryOption(
      name: "Cayman Islands",
      code: "KY",
      dialCode: "+1-345",
      flag: "🇰🇾",
    ),
    CountryOption(
      name: "Central African Republic",
      code: "CF",
      dialCode: "+236",
      flag: "🇨🇫",
    ),
    CountryOption(name: "Chad", code: "TD", dialCode: "+235", flag: "🇹🇩"),
    CountryOption(name: "Chile", code: "CL", dialCode: "+56", flag: "🇨🇱"),
    CountryOption(name: "China", code: "CN", dialCode: "+86", flag: "🇨🇳"),
    CountryOption(
      name: "Christmas Island",
      code: "CX",
      dialCode: "+61",
      flag: "🇨🇽",
    ),
    CountryOption(
      name: "Cocos Islands",
      code: "CC",
      dialCode: "+61",
      flag: "🇨🇨",
    ),
    CountryOption(name: "Colombia", code: "CO", dialCode: "+57", flag: "🇨🇴"),
    CountryOption(name: "Comoros", code: "KM", dialCode: "+269", flag: "🇰🇲"),
    CountryOption(
      name: "Cook Islands",
      code: "CK",
      dialCode: "+682",
      flag: "🇨🇰",
    ),
    CountryOption(
      name: "Costa Rica",
      code: "CR",
      dialCode: "+506",
      flag: "🇨🇷",
    ),
    CountryOption(name: "Croatia", code: "HR", dialCode: "+385", flag: "🇭🇷"),
    CountryOption(name: "Cuba", code: "CU", dialCode: "+53", flag: "🇨🇺"),
    CountryOption(name: "Curacao", code: "CW", dialCode: "+599", flag: "🇨🇼"),
    CountryOption(name: "Cyprus", code: "CY", dialCode: "+357", flag: "🇨🇾"),
    CountryOption(
      name: "Czech Republic",
      code: "CZ",
      dialCode: "+420",
      flag: "🇨🇿",
    ),
    CountryOption(
      name: "Democratic Republic of the Congo",
      code: "CD",
      dialCode: "+243",
      flag: "🇨🇩",
    ),
    CountryOption(name: "Denmark", code: "DK", dialCode: "+45", flag: "🇩🇰"),
    CountryOption(name: "Djibouti", code: "DJ", dialCode: "+253", flag: "🇩🇯"),
    CountryOption(
      name: "Dominica",
      code: "DM",
      dialCode: "+1-767",
      flag: "🇩🇲",
    ),
    CountryOption(
      name: "Dominican Republic",
      code: "DO",
      dialCode: "+1-809, 1-829, 1-849",
      flag: "🇩🇴",
    ),
    CountryOption(
      name: "East Timor",
      code: "TL",
      dialCode: "+670",
      flag: "🇹🇱",
    ),
    CountryOption(name: "Ecuador", code: "EC", dialCode: "+593", flag: "🇪🇨"),
    CountryOption(name: "Egypt", code: "EG", dialCode: "+20", flag: "🇪🇬"),
    CountryOption(
      name: "El Salvador",
      code: "SV",
      dialCode: "+503",
      flag: "🇸🇻",
    ),
    CountryOption(
      name: "Equatorial Guinea",
      code: "GQ",
      dialCode: "+240",
      flag: "🇬🇶",
    ),
    CountryOption(name: "Eritrea", code: "ER", dialCode: "+291", flag: "🇪🇷"),
    CountryOption(name: "Estonia", code: "EE", dialCode: "+372", flag: "🇪🇪"),
    CountryOption(name: "Ethiopia", code: "ET", dialCode: "+251", flag: "🇪🇹"),
    CountryOption(
      name: "Falkland Islands",
      code: "FK",
      dialCode: "+500",
      flag: "🇫🇰",
    ),
    CountryOption(
      name: "Faroe Islands",
      code: "FO",
      dialCode: "+298",
      flag: "🇫🇴",
    ),
    CountryOption(name: "Fiji", code: "FJ", dialCode: "+679", flag: "🇫🇯"),
    CountryOption(name: "Finland", code: "FI", dialCode: "+358", flag: "🇫🇮"),
    CountryOption(name: "France", code: "FR", dialCode: "+33", flag: "🇫🇷"),
    CountryOption(
      name: "French Polynesia",
      code: "PF",
      dialCode: "+689",
      flag: "🇵🇫",
    ),
    CountryOption(name: "Gabon", code: "GA", dialCode: "+241", flag: "🇬🇦"),
    CountryOption(name: "Gambia", code: "GM", dialCode: "+220", flag: "🇬🇲"),
    CountryOption(name: "Georgia", code: "GE", dialCode: "+995", flag: "🇬🇪"),
    CountryOption(name: "Germany", code: "DE", dialCode: "+49", flag: "🇩🇪"),
    CountryOption(name: "Ghana", code: "GH", dialCode: "+233", flag: "🇬🇭"),
    CountryOption(
      name: "Gibraltar",
      code: "GI",
      dialCode: "+350",
      flag: "🇬🇮",
    ),
    CountryOption(name: "Greece", code: "GR", dialCode: "+30", flag: "🇬🇷"),
    CountryOption(
      name: "Greenland",
      code: "GL",
      dialCode: "+299",
      flag: "🇬🇱",
    ),
    CountryOption(
      name: "Grenada",
      code: "GD",
      dialCode: "+1-473",
      flag: "🇬🇩",
    ),
    CountryOption(name: "Guam", code: "GU", dialCode: "+1-671", flag: "🇬🇺"),
    CountryOption(
      name: "Guatemala",
      code: "GT",
      dialCode: "+502",
      flag: "🇬🇹",
    ),
    CountryOption(
      name: "Guernsey",
      code: "GG",
      dialCode: "+44-1481",
      flag: "🇬🇬",
    ),
    CountryOption(name: "Guinea", code: "GN", dialCode: "+224", flag: "🇬🇳"),
    CountryOption(
      name: "Guinea-Bissau",
      code: "GW",
      dialCode: "+245",
      flag: "🇬🇼",
    ),
    CountryOption(name: "Guyana", code: "GY", dialCode: "+592", flag: "🇬🇾"),
    CountryOption(name: "Haiti", code: "HT", dialCode: "+509", flag: "🇭🇹"),
    CountryOption(name: "Honduras", code: "HN", dialCode: "+504", flag: "🇭🇳"),
    CountryOption(
      name: "Hong Kong",
      code: "HK",
      dialCode: "+852",
      flag: "🇭🇰",
    ),
    CountryOption(name: "Hungary", code: "HU", dialCode: "+36", flag: "🇭🇺"),
    CountryOption(name: "Iceland", code: "IS", dialCode: "+354", flag: "🇮🇸"),
    CountryOption(name: "India", code: "IN", dialCode: "+91", flag: "🇮🇳"),
    CountryOption(name: "Indonesia", code: "ID", dialCode: "+62", flag: "🇮🇩"),
    CountryOption(name: "Iran", code: "IR", dialCode: "+98", flag: "🇮🇷"),
    CountryOption(name: "Iraq", code: "IQ", dialCode: "+964", flag: "🇮🇶"),
    CountryOption(name: "Ireland", code: "IE", dialCode: "+353", flag: "🇮🇪"),
    CountryOption(
      name: "Isle of Man",
      code: "IM",
      dialCode: "+44-1624",
      flag: "🇮🇲",
    ),
    CountryOption(name: "Israel", code: "IL", dialCode: "+972", flag: "🇮🇱"),
    CountryOption(name: "Italy", code: "IT", dialCode: "+39", flag: "🇮🇹"),
    CountryOption(
      name: "Ivory Coast",
      code: "CI",
      dialCode: "+225",
      flag: "🇨🇮",
    ),
    CountryOption(
      name: "Jamaica",
      code: "JM",
      dialCode: "+1-876",
      flag: "🇯🇲",
    ),
    CountryOption(name: "Japan", code: "JP", dialCode: "+81", flag: "🇯🇵"),
    CountryOption(
      name: "Jersey",
      code: "JE",
      dialCode: "+44-1534",
      flag: "🇯🇪",
    ),
    CountryOption(name: "Jordan", code: "JO", dialCode: "+962", flag: "🇯🇴"),
    CountryOption(name: "Kazakhstan", code: "KZ", dialCode: "+7", flag: "🇰🇿"),
    CountryOption(name: "Kenya", code: "KE", dialCode: "+254", flag: "🇰🇪"),
    CountryOption(name: "Kiribati", code: "KI", dialCode: "+686", flag: "🇰🇮"),
    CountryOption(name: "Kosovo", code: "XK", dialCode: "+383", flag: "🇽🇰"),
    CountryOption(name: "Kuwait", code: "KW", dialCode: "+965", flag: "🇰🇼"),
    CountryOption(
      name: "Kyrgyzstan",
      code: "KG",
      dialCode: "+996",
      flag: "🇰🇬",
    ),
    CountryOption(name: "Laos", code: "LA", dialCode: "+856", flag: "🇱🇦"),
    CountryOption(name: "Latvia", code: "LV", dialCode: "+371", flag: "🇱🇻"),
    CountryOption(name: "Lebanon", code: "LB", dialCode: "+961", flag: "🇱🇧"),
    CountryOption(name: "Lesotho", code: "LS", dialCode: "+266", flag: "🇱🇸"),
    CountryOption(name: "Liberia", code: "LR", dialCode: "+231", flag: "🇱🇷"),
    CountryOption(name: "Libya", code: "LY", dialCode: "+218", flag: "🇱🇾"),
    CountryOption(
      name: "Liechtenstein",
      code: "LI",
      dialCode: "+423",
      flag: "🇱🇮",
    ),
    CountryOption(
      name: "Lithuania",
      code: "LT",
      dialCode: "+370",
      flag: "🇱🇹",
    ),
    CountryOption(
      name: "Luxembourg",
      code: "LU",
      dialCode: "+352",
      flag: "🇱🇺",
    ),
    CountryOption(name: "Macau", code: "MO", dialCode: "+853", flag: "🇲🇴"),
    CountryOption(
      name: "Macedonia",
      code: "MK",
      dialCode: "+389",
      flag: "🇲🇰",
    ),
    CountryOption(
      name: "Madagascar",
      code: "MG",
      dialCode: "+261",
      flag: "🇲🇬",
    ),
    CountryOption(name: "Malawi", code: "MW", dialCode: "+265", flag: "🇲🇼"),
    CountryOption(name: "Malaysia", code: "MY", dialCode: "+60", flag: "🇲🇾"),
    CountryOption(name: "Maldives", code: "MV", dialCode: "+960", flag: "🇲🇻"),
    CountryOption(name: "Mali", code: "ML", dialCode: "+223", flag: "🇲🇱"),
    CountryOption(name: "Malta", code: "MT", dialCode: "+356", flag: "🇲🇹"),
    CountryOption(
      name: "Marshall Islands",
      code: "MH",
      dialCode: "+692",
      flag: "🇲🇭",
    ),
    CountryOption(
      name: "Mauritania",
      code: "MR",
      dialCode: "+222",
      flag: "🇲🇷",
    ),
    CountryOption(
      name: "Mauritius",
      code: "MU",
      dialCode: "+230",
      flag: "🇲🇺",
    ),
    CountryOption(name: "Mayotte", code: "YT", dialCode: "+262", flag: "🇾🇹"),
    CountryOption(name: "Mexico", code: "MX", dialCode: "+52", flag: "🇲🇽"),
    CountryOption(
      name: "Micronesia",
      code: "FM",
      dialCode: "+691",
      flag: "🇫🇲",
    ),
    CountryOption(name: "Moldova", code: "MD", dialCode: "+373", flag: "🇲🇩"),
    CountryOption(name: "Monaco", code: "MC", dialCode: "+377", flag: "🇲🇨"),
    CountryOption(name: "Mongolia", code: "MN", dialCode: "+976", flag: "🇲🇳"),
    CountryOption(
      name: "Montenegro",
      code: "ME",
      dialCode: "+382",
      flag: "🇲🇪",
    ),
    CountryOption(
      name: "Montserrat",
      code: "MS",
      dialCode: "+1-664",
      flag: "🇲🇸",
    ),
    CountryOption(name: "Morocco", code: "MA", dialCode: "+212", flag: "🇲🇦"),
    CountryOption(
      name: "Mozambique",
      code: "MZ",
      dialCode: "+258",
      flag: "🇲🇿",
    ),
    CountryOption(name: "Myanmar", code: "MM", dialCode: "+95", flag: "🇲🇲"),
    CountryOption(name: "Namibia", code: "NA", dialCode: "+264", flag: "🇳🇦"),
    CountryOption(name: "Nauru", code: "NR", dialCode: "+674", flag: "🇳🇷"),
    CountryOption(name: "Nepal", code: "NP", dialCode: "+977", flag: "🇳🇵"),
    CountryOption(
      name: "Netherlands",
      code: "NL",
      dialCode: "+31",
      flag: "🇳🇱",
    ),
    CountryOption(
      name: "Netherlands Antilles",
      code: "AN",
      dialCode: "+599",
      flag: "🇳🇱",
    ),
    CountryOption(
      name: "New Caledonia",
      code: "NC",
      dialCode: "+687",
      flag: "🇳🇨",
    ),
    CountryOption(
      name: "New Zealand",
      code: "NZ",
      dialCode: "+64",
      flag: "🇳🇿",
    ),
    CountryOption(
      name: "Nicaragua",
      code: "NI",
      dialCode: "+505",
      flag: "🇳🇮",
    ),
    CountryOption(name: "Niger", code: "NE", dialCode: "+227", flag: "🇳🇪"),
    CountryOption(name: "Nigeria", code: "NG", dialCode: "+234", flag: "🇳🇬"),
    CountryOption(name: "Niue", code: "NU", dialCode: "+683", flag: "🇳🇺"),
    CountryOption(
      name: "North Korea",
      code: "KP",
      dialCode: "+850",
      flag: "🇰🇵",
    ),
    CountryOption(
      name: "Northern Mariana Islands",
      code: "MP",
      dialCode: "+1-670",
      flag: "🇲🇵",
    ),
    CountryOption(name: "Norway", code: "NO", dialCode: "+47", flag: "🇳🇴"),
    CountryOption(name: "Oman", code: "OM", dialCode: "+968", flag: "🇴🇲"),
    CountryOption(name: "Pakistan", code: "PK", dialCode: "+92", flag: "🇵🇰"),
    CountryOption(name: "Palau", code: "PW", dialCode: "+680", flag: "🇵🇼"),
    CountryOption(
      name: "Palestine",
      code: "PS",
      dialCode: "+970",
      flag: "🇵🇸",
    ),
    CountryOption(name: "Panama", code: "PA", dialCode: "+507", flag: "🇵🇦"),
    CountryOption(
      name: "Papua New Guinea",
      code: "PG",
      dialCode: "+675",
      flag: "🇵🇬",
    ),
    CountryOption(name: "Paraguay", code: "PY", dialCode: "+595", flag: "🇵🇾"),
    CountryOption(name: "Peru", code: "PE", dialCode: "+51", flag: "🇵🇪"),
    CountryOption(
      name: "Philippines",
      code: "PH",
      dialCode: "+63",
      flag: "🇵🇭",
    ),
    CountryOption(name: "Pitcairn", code: "PN", dialCode: "+64", flag: "🇵🇳"),
    CountryOption(name: "Poland", code: "PL", dialCode: "+48", flag: "🇵🇱"),
    CountryOption(name: "Portugal", code: "PT", dialCode: "+351", flag: "🇵🇹"),
    CountryOption(
      name: "Puerto Rico",
      code: "PR",
      dialCode: "+1-787, 1-939",
      flag: "🇵🇷",
    ),
    CountryOption(name: "Qatar", code: "QA", dialCode: "+974", flag: "🇶🇦"),
    CountryOption(
      name: "Republic of the Congo",
      code: "CG",
      dialCode: "+242",
      flag: "🇨🇬",
    ),
    CountryOption(name: "Reunion", code: "RE", dialCode: "+262", flag: "🇷🇪"),
    CountryOption(name: "Romania", code: "RO", dialCode: "+40", flag: "🇷🇴"),
    CountryOption(name: "Russia", code: "RU", dialCode: "+7", flag: "🇷🇺"),
    CountryOption(name: "Rwanda", code: "RW", dialCode: "+250", flag: "🇷🇼"),
    CountryOption(
      name: "Saint Barthelemy",
      code: "BL",
      dialCode: "+590",
      flag: "🇧🇱",
    ),
    CountryOption(
      name: "Saint Helena",
      code: "SH",
      dialCode: "+290",
      flag: "🇸🇭",
    ),
    CountryOption(
      name: "Saint Kitts and Nevis",
      code: "KN",
      dialCode: "+1-869",
      flag: "🇰🇳",
    ),
    CountryOption(
      name: "Saint Lucia",
      code: "LC",
      dialCode: "+1-758",
      flag: "🇱🇨",
    ),
    CountryOption(
      name: "Saint Martin",
      code: "MF",
      dialCode: "+590",
      flag: "🇲🇫",
    ),
    CountryOption(
      name: "Saint Pierre and Miquelon",
      code: "PM",
      dialCode: "+508",
      flag: "🇵🇲",
    ),
    CountryOption(
      name: "Saint Vincent and the Grenadines",
      code: "VC",
      dialCode: "+1-784",
      flag: "🇻🇨",
    ),
    CountryOption(name: "Samoa", code: "WS", dialCode: "+685", flag: "🇼🇸"),
    CountryOption(
      name: "San Marino",
      code: "SM",
      dialCode: "+378",
      flag: "🇸🇲",
    ),
    CountryOption(
      name: "Sao Tome and Principe",
      code: "ST",
      dialCode: "+239",
      flag: "🇸🇹",
    ),
    CountryOption(
      name: "Saudi Arabia",
      code: "SA",
      dialCode: "+966",
      flag: "🇸🇦",
    ),
    CountryOption(name: "Senegal", code: "SN", dialCode: "+221", flag: "🇸🇳"),
    CountryOption(name: "Serbia", code: "RS", dialCode: "+381", flag: "🇷🇸"),
    CountryOption(
      name: "Seychelles",
      code: "SC",
      dialCode: "+248",
      flag: "🇸🇨",
    ),
    CountryOption(
      name: "Sierra Leone",
      code: "SL",
      dialCode: "+232",
      flag: "🇸🇱",
    ),
    CountryOption(name: "Singapore", code: "SG", dialCode: "+65", flag: "🇸🇬"),
    CountryOption(
      name: "Sint Maarten",
      code: "SX",
      dialCode: "+1-721",
      flag: "🇸🇽",
    ),
    CountryOption(name: "Slovakia", code: "SK", dialCode: "+421", flag: "🇸🇰"),
    CountryOption(name: "Slovenia", code: "SI", dialCode: "+386", flag: "🇸🇮"),
    CountryOption(
      name: "Solomon Islands",
      code: "SB",
      dialCode: "+677",
      flag: "🇸🇧",
    ),
    CountryOption(name: "Somalia", code: "SO", dialCode: "+252", flag: "🇸🇴"),
    CountryOption(
      name: "South Africa",
      code: "ZA",
      dialCode: "+27",
      flag: "🇿🇦",
    ),
    CountryOption(
      name: "South Korea",
      code: "KR",
      dialCode: "+82",
      flag: "🇰🇷",
    ),
    CountryOption(
      name: "South Sudan",
      code: "SS",
      dialCode: "+211",
      flag: "🇸🇸",
    ),
    CountryOption(name: "Spain", code: "ES", dialCode: "+34", flag: "🇪🇸"),
    CountryOption(name: "Sri Lanka", code: "LK", dialCode: "+94", flag: "🇱🇰"),
    CountryOption(name: "Sudan", code: "SD", dialCode: "+249", flag: "🇸🇩"),
    CountryOption(name: "Suriname", code: "SR", dialCode: "+597", flag: "🇸🇷"),
    CountryOption(
      name: "Svalbard and Jan Mayen",
      code: "SJ",
      dialCode: "+47",
      flag: "🇸🇯",
    ),
    CountryOption(
      name: "Swaziland",
      code: "SZ",
      dialCode: "+268",
      flag: "🇸🇿",
    ),
    CountryOption(name: "Sweden", code: "SE", dialCode: "+46", flag: "🇸🇪"),
    CountryOption(
      name: "Switzerland",
      code: "CH",
      dialCode: "+41",
      flag: "🇨🇭",
    ),
    CountryOption(name: "Syria", code: "SY", dialCode: "+963", flag: "🇸🇾"),
    CountryOption(name: "Taiwan", code: "TW", dialCode: "+886", flag: "🇹🇼"),
    CountryOption(
      name: "Tajikistan",
      code: "TJ",
      dialCode: "+992",
      flag: "🇹🇯",
    ),
    CountryOption(name: "Tanzania", code: "TZ", dialCode: "+255", flag: "🇹🇿"),
    CountryOption(name: "Thailand", code: "TH", dialCode: "+66", flag: "🇹🇭"),
    CountryOption(name: "Togo", code: "TG", dialCode: "+228", flag: "🇹🇬"),
    CountryOption(name: "Tokelau", code: "TK", dialCode: "+690", flag: "🇹🇰"),
    CountryOption(name: "Tonga", code: "TO", dialCode: "+676", flag: "🇹🇴"),
    CountryOption(
      name: "Trinidad and Tobago",
      code: "TT",
      dialCode: "+1-868",
      flag: "🇹🇹",
    ),
    CountryOption(name: "Tunisia", code: "TN", dialCode: "+216", flag: "🇹🇳"),
    CountryOption(name: "Turkey", code: "TR", dialCode: "+90", flag: "🇹🇷"),
    CountryOption(
      name: "Turkmenistan",
      code: "TM",
      dialCode: "+993",
      flag: "🇹🇲",
    ),
    CountryOption(
      name: "Turks and Caicos Islands",
      code: "TC",
      dialCode: "+1-649",
      flag: "🇹🇨",
    ),
    CountryOption(name: "Tuvalu", code: "TV", dialCode: "+688", flag: "🇹🇻"),
    CountryOption(
      name: "U.S. Virgin Islands",
      code: "VI",
      dialCode: "+1-340",
      flag: "🇻🇮",
    ),
    CountryOption(name: "Uganda", code: "UG", dialCode: "+256", flag: "🇺🇬"),
    CountryOption(name: "Ukraine", code: "UA", dialCode: "+380", flag: "🇺🇦"),
    CountryOption(
      name: "United Arab Emirates",
      code: "AE",
      dialCode: "+971",
      flag: "🇦🇪",
    ),
    CountryOption(
      name: "United Kingdom",
      code: "GB",
      dialCode: "+44",
      flag: "🇬🇧",
    ),
    CountryOption(
      name: "United States",
      code: "US",
      dialCode: "+1",
      flag: "🇺🇸",
    ),
    CountryOption(name: "Uruguay", code: "UY", dialCode: "+598", flag: "🇺🇾"),
    CountryOption(
      name: "Uzbekistan",
      code: "UZ",
      dialCode: "+998",
      flag: "🇺🇿",
    ),
    CountryOption(name: "Vanuatu", code: "VU", dialCode: "+678", flag: "🇻🇺"),
    CountryOption(name: "Vatican", code: "VA", dialCode: "+379", flag: "🇻🇦"),
    CountryOption(name: "Venezuela", code: "VE", dialCode: "+58", flag: "🇻🇪"),
    CountryOption(name: "Vietnam", code: "VN", dialCode: "+84", flag: "🇻🇳"),
    CountryOption(
      name: "Wallis and Futuna",
      code: "WF",
      dialCode: "+681",
      flag: "🇼🇫",
    ),
    CountryOption(
      name: "Western Sahara",
      code: "EH",
      dialCode: "+212",
      flag: "🇪🇭",
    ),
    CountryOption(name: "Yemen", code: "YE", dialCode: "+967", flag: "🇾🇪"),
    CountryOption(name: "Zambia", code: "ZM", dialCode: "+260", flag: "🇿🇲"),
    CountryOption(name: "Zimbabwe", code: "ZW", dialCode: "+263", flag: "🇿🇼"),
  ];

  static CountryOption getOption(String code) {
    return countries.firstWhere(
      (opt) => opt.code == code,
      orElse: () => countries.firstWhere((opt) => opt.code == 'US'),
    );
  }
}
